properties([pipelineTriggers([githubPush()])])

pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
              echo 'Building...'
              sh '/home/ld-admin/build.sh 3.4.0 '
            }
        }
        stage('Upgrade') {
            steps {
              echo 'Upgrading...'
              ansiblePlaybook(
                  playbook: '/home/ld-admin/ansible/upgrade/playbook.yml', 
                  inventory: 'inventory.ini',
                  extraVars: [
                      ansible_become_pass: [
                          value: """${sh(
                            returnStdout: true,
                            script: 'cat /tmp/become_pass'
                          )}""", 
                          hidden: true
                      ]
                  ]
              )
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
    }
}

