- name: Start Build
  hosts: localhost

  vars_prompt:

  - name: mgmt_ip
    prompt: MGMT Server IP
    confirm: yes
    private: no

  - name: old_version
    prompt: Current MGMT Server Version
    confirm: yes
    private: no

  - name: new_version
    prompt: New MGMT Server Version
    confirm: yes
    private: no

  - name: rc
    prompt: Release Candidate Number
    confirm: yes
    private: no

  - name: packages
    prompt: Packages to install (space seperated)
    private: no

  tasks:

  - name: Set release candidate
    set_fact:
      rc: "-rc{{ rc }}"
    when: rc != ""

  - name: Set packages list
    set_fact:
      packages: "{{ packages.split(' ') if packages != '' else [] }}"

  - name: Create Jenkinsfile
    template:
      src: templates/Jenkinsfile.j2
      dest: Jenkinsfile

  - name: Create invnentory.ini
    template:
      src: templates/inventory.j2
      dest: inventory.ini

  - name: Git add
    shell: git add .

  - name: Git commit
    shell: "git commit -m 'Building firmware for {{ new_version }}{{ rc }}'"

  - name: Git push
    shell: git push
